services:
  - type: web
    name: edumanage-school-erp
    env: python
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "gunicorn school_erp.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.8"
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_qfPUM0B2ORhi@ep-cold-river-awfrnqdh.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
