# Generated by Django 4.2.30 on 2026-09-23 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fees.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0005_activate_notices'),
        ('students', '0003_alter_student_address_alter_student_admission_date_and_more'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feehead',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='feepayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='status',
            field=models.CharField(choices=[('VERIFIED', 'Verified / Active'), ('REVERSED', 'Reversed / Voided'), ('REFUNDED', 'Refunded')], default='VERIFIED', max_length=20),
        ),
        migrations.AddField(
            model_name='feepayment',
            name='verification_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='feehead',
            name='name',
            field=models.CharField(help_text='e.g. Tuition Fee, Admission Fee, Exam Fee, Transport Fee', max_length=100),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash Counter Collection'), ('UPI', 'UPI / QR Code'), ('BANK_TRANSFER', 'Bank Transfer / NEFT / IMPS'), ('ONLINE', 'Online Payment Gateway'), ('CHEQUE', 'Cheque / Bank Draft'), ('CARD', 'Debit / Credit Card'), ('OTHER', 'Other')], default='CASH', max_length=30),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='receipt_no',
            field=models.CharField(help_text='e.g. REC-2026-000001', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending / Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_no', models.CharField(help_text='Generated claim ID, e.g. CLM-2026-000001', max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('UPI', 'UPI / QR Code (GPay, PhonePe, Paytm, etc.)'), ('BANK_TRANSFER', 'Bank Transfer / NEFT / IMPS / RTGS'), ('NET_BANKING', 'Net Banking'), ('CHEQUE', 'Cheque / Demand Draft'), ('CASH_DEPOSIT', 'Cash Deposit in School Bank A/C'), ('CARD', 'Debit / Credit Card'), ('OTHER', 'Other Payment Mode')], default='UPI', max_length=30)),
                ('transaction_id', models.CharField(help_text='UTR / Transaction / Cheque / Reference ID', max_length=100)),
                ('bank_name', models.CharField(blank=True, help_text='Bank / UPI App name', max_length=100)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to=fees.models.secure_fee_proof_path)),
                ('student_note', models.TextField(blank=True, help_text='Optional note from student/parent')),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified & Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by Student')], default='PENDING_VERIFICATION', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_submissions', to='students.student')),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='fees.studentfee')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_fee_claims', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_fee_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_no', models.CharField(help_text='e.g. REF-2026-000001', max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_mode', models.CharField(default='BANK_TRANSFER', max_length=30)),
                ('reason', models.TextField(help_text='Reason for refund / chargeback')),
                ('transaction_ref', models.CharField(blank=True, help_text='Bank refund transfer UTR', max_length=100)),
                ('status', models.CharField(choices=[('REQUESTED', 'Refund Requested'), ('APPROVED', 'Refund Approved'), ('PROCESSED', 'Refund Processed / Completed'), ('REJECTED', 'Refund Rejected')], default='REQUESTED', max_length=30)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_approvals', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='fees.feepayment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. PAYMENT_CLAIM_SUBMITTED, PAYMENT_APPROVED, PAYMENT_REJECTED, PAYMENT_REVERSED, FEE_ADJUSTMENT, REFUND_PROCESSED', max_length=60)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('old_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.feepayment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
                ('student_fee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.studentfee')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fees.paymentsubmission')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('DISCOUNT', 'Discount / Concession / Scholarship'), ('FINE', 'Late Fine / Penalty'), ('CORRECTION', 'Ledger Correction / Balance Fix'), ('WAIVER', 'Special Waiver')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Adjustment amount', max_digits=10)),
                ('reason', models.TextField(help_text='Mandatory detailed explanation for this adjustment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='fees.studentfee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='feepayment',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_payment', to='fees.paymentsubmission'),
        ),
        migrations.CreateModel(
            name='DailyFeeClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_date', models.DateField()),
                ('cash_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('upi_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bank_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cheque_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('online_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('other_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_refunded', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_closing', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'ordering': ['-closing_date'],
                'unique_together': {('school', 'closing_date')},
            },
        ),
    ]
