# Generated by Django 4.2.30 on 2026-09-23 09:50

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_feehead_options_feepayment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeauditlog',
            name='details',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
