# Generated by Django 5.2.17 on 2026-08-11 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('qualification', models.CharField(help_text='e.g. M.Sc. Physics, B.Ed.', max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('joining_date', models.DateField()),
                ('assigned_classes', models.ManyToManyField(blank=True, related_name='assigned_teachers', to='academics.class')),
                ('assigned_sections', models.ManyToManyField(blank=True, related_name='assigned_teachers', to='academics.section')),
                ('assigned_subjects', models.ManyToManyField(blank=True, related_name='assigned_teachers', to='academics.subject')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'employee_id'],
                'unique_together': {('school', 'employee_id')},
            },
        ),
    ]
