# Generated by Django 5.2.17 on 2026-08-11 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='School Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='School Code / Slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('principal_name', models.CharField(blank=True, max_length=150, verbose_name='Principal Name')),
                ('affiliation_no', models.CharField(blank=True, max_length=100, verbose_name='Affiliation No.')),
                ('established_year', models.IntegerField(blank=True, null=True, verbose_name='Established Year')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('target_role', models.CharField(choices=[('ALL', 'All (Entire School)'), ('TEACHER', 'Teachers Only'), ('STUDENT', 'Students Only'), ('PARENT', 'Parents Only')], default='ALL', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2025-2026', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_sessions', to='schools.school')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('school', 'name')},
            },
        ),
    ]
