# Generated by Django 4.2.30 on 2026-09-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='school',
            name='affiliation_no',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Affiliation No.'),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='school',
            name='principal_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Principal Name'),
        ),
    ]
