# Generated by Django 4.2.30 on 2026-09-29 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_activate_notices'),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_periods', models.PositiveIntegerField(default=8, help_text='Total number of periods (e.g. 5, 6, 7, 8)')),
                ('break_after_period', models.PositiveIntegerField(default=4, help_text='Recess / Lunch break falls after this period')),
                ('break_start_time', models.TimeField(default='11:40:00')),
                ('break_end_time', models.TimeField(default='12:20:00')),
                ('has_break', models.BooleanField(default=True)),
                ('class_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_settings', to='academics.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'verbose_name': 'Timetable Setting',
                'verbose_name_plural': 'Timetable Settings',
                'ordering': ['class_level'],
            },
        ),
    ]
