# Generated by Django 4.2.30 on 2026-09-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_timetablesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablesetting',
            name='period_timings',
            field=models.JSONField(blank=True, default=dict, help_text='Custom period start/end timings dictionary'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
