# Generated by Django 5.2.17 on 2026-08-11 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Term-1 Half Yearly Exam', max_length=150)),
                ('exam_type', models.CharField(choices=[('UNIT_TEST', 'Unit Test'), ('MONTHLY', 'Monthly Test'), ('HALF_YEARLY', 'Half Yearly Examination'), ('PRE_BOARD', 'Pre-Board Examination'), ('ANNUAL', 'Annual Examination'), ('CUSTOM', 'Custom Assessment')], default='UNIT_TEST', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_published', models.BooleanField(default=False, verbose_name='Publish Result')),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='schools.academicsession')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarksEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_marks_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('practical_marks_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_marks_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('is_pass', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_entries', to='examinations.exam')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.subject')),
            ],
            options={
                'ordering': ['student', 'subject'],
                'unique_together': {('school', 'exam', 'student', 'subject')},
            },
        ),
    ]
